title: MyProject (GitHub)
theme: minima
author: Dziaukas
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Git is an open-source version control system that was started by Linus Torvalds—the same person who created Linux.
  Git is a command-line tool, but the center around which all things involving Git revolve is the hub—GitHub.com—where
  developers store their projects and network with like minded people.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
